flag:
  DO_FREE_FORECAST: 'none'
  FRAC_GRID: 'YES'
  IC_FROM_FIX_DIR: 'YES'
  OBS_GHCN_SNOW: 'NO'
  OBS_IMS_SNOW: 'NO'
  OBS_SFCSNO: 'NO'
  OBS_SMAP: 'NO'
  OBS_SMOPS: 'NO'
path:
  PTMP: None
  WARMSTART_DIR: None
parm:
  ACCOUNT: epic
  APP: S2SWA
  DATE_CYCLE_FREQ_HR: 24
  DATE_FIRST_CYCLE: 202103220600
  DATE_LAST_CYCLE: 202103230600
  EXP_CASE_NAME: None
  IC_DATA_MODEL: gfs
  MACHINE: /machine/platform/name
  PY_LOG_LEVEL: INFO

