prepend_path("MODULEPATH", os.getenv("modulepath_spack_stack"))
load(pathJoin("stack-intel", stack_intel_ver))
load(pathJoin("stack-cray-mpich", stack_cray_mpich_ver))
load(pathJoin("jasper", jasper_ver))
load(pathJoin("hdf5", hdf5_ver))
load(pathJoin("netcdf-c", netcdf_c_ver))
load(pathJoin("netcdf-fortran", netcdf_fortran_ver))
load(pathJoin("parallelio", parallelio_ver))
load(pathJoin("esmf", esmf_ver))
load(pathJoin("g2", g2_ver))
load(pathJoin("prod_util", prod_util_ver))

prepend_path("MODULEPATH", "/ncrc/proj/epic/spack-stack/c6/spack-stack-1.9.2/envs/ue-intel-2023.2.0/install/modulefiles/gcc/12.3.0")
load("ecflow/5.11.4")

prepend_path("MODULEPATH", os.getenv("modulepath_pymodule"))
load("python-ufs-land-da-wflow")
