ACCOUNT: epic
APP: NG-GODAS
COLDSTART: 'YES'
DATE_CYCLE_FREQ_HR: 12
DATE_FIRST_CYCLE: 2021032206
DATE_LAST_CYCLE: 2021032218
DO_FREE_FORECAST: all
DT_ATMOS: 900
DT_RUNSEQ: 3600
envir: ng_fcst_cycle
EXP_CASE_NAME: ng_freefcst_cycle
FCST_HRS: 12
IC_FROM_FIX_DIR: 'YES'
NPROCS_ICE: 12
NPROCS_OCN: 16
NPZ: 127
OUTPUT_FH: '6 -1'
RES: 96
