ACCOUNT: epic
APP: NG-GODAS
COLDSTART: 'NO'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2021032206
DATE_LAST_CYCLE: 2021032218
DATM_DATA_TYPE: gefs
DO_FREE_FORECAST: first
DT_ATMOS: 900
DT_RUNSEQ: 1800
envir: ng_soca_gefs
EXP_CASE_NAME: ng_soca_gefs
FCST_HRS: 24
NPROCS_DATM: 16
NPROCS_ICE: 24
NPROCS_OCN: 100
NPZ: 127
OUTPUT_FH: '6 -1'
RES: 96
