flag:
  COLDSTART: 'NO'
  JEDI_TYPE_FV3: 'YES'
  JEDI_TYPE_SNOW: 'NO'
  JEDI_TYPE_SOCA: 'NO'
path:
parm:
  ACCOUNT: epic
  APP: ATM
  ATM_LAYOUT_X: 2
  ATM_LAYOUT_Y: 2
  CCPP_SUITE: FV3_GFS_v17_p8_ugwpv1
  DATE_CYCLE_FREQ_HR: 24
  DATE_FIRST_CYCLE: 2024022318
  DATE_LAST_CYCLE: 2024022418
  DT_ATMOS: 600
  envir: atm_atmDA_3dvar_ecf
  EXP_CASE_NAME: atm_atmDA_3dvar_ecf
  FCST_HRS: 24
  HISTORY_FILE_ON_NATIVE_GRID: .true.
  ICHUNK2D: 384
  ICHUNK3D: 384
  IMO: 384
  JCHUNK2D: 192
  JCHUNK3D: 192
  JEDI_ALGORITHM: 3dvar
  JMO: 192
  KCHUNK3D: 1
  OUTPUT_FH: '6 -1'
  OUTPUT_GRID: gaussian_grid
  QUILTING_RESTART: .true.
  WORKFLOW_MANAGER: ecflow
  ZSTANDARD_LEVEL: 0

