flag:
  COLDSTART: 'YES'
  DO_FREE_FORECAST: first
  IC_FROM_FIX_DIR: 'YES'
path:
parm:
  ACCOUNT: epic
  APP: S2SWA
  DATE_CYCLE_FREQ_HR: 24
  DATE_FIRST_CYCLE: 2021032206
  DATE_LAST_CYCLE: 2021032206
  DT_ATMOS: 720
  DT_RUNSEQ: 3600
  envir: fcst_baseline
  EXP_CASE_NAME: s2swa_freefcst_baseline
  FCST_HRS: 24
  OUTPUT_FH: '6 -1'

