ACCOUNT: epic
APP: NG-GODAS
COLDSTART: 'NO'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2021032206
DATE_LAST_CYCLE: 2021032218
DATM_DATA_TYPE: gfs
DO_FREE_FORECAST: first
DT_ATMOS: 900
DT_RUNSEQ: 3600
envir: ng_soca_gefs
EXP_CASE_NAME: ng_soca_gefs
FCST_HRS: 24
NPROCS_ICE: 12
NPROCS_OCN: 16
NPZ: 127
OUTPUT_FH: '6 -1'
RES: 96
