ACCOUNT: epic
APP: NG-GODAS
COLDSTART: 'NO'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2018041500
DATE_LAST_CYCLE: 2018041500
DATM_DATA_TYPE: gfs
DO_FREE_FORECAST: none
DT_ATMOS: 900
DT_MOM6: 900
DT_RUNSEQ: 1800
envir: ng_soca_3dvar
EXP_CASE_NAME: ng_soca_3dvar
JEDI_TYPE_SOCA: 'YES'
FCST_HRS: 24
NPROCS_DATM: 12
NPROCS_ICE: 12
NPROCS_OCN: 16
NPZ: 127
OUTPUT_FH: '6 -1'
RES: 96
