ACCOUNT: epic
APP: NG-GODAS
COLDSTART: 'YES'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2011100100
DATE_LAST_CYCLE: 2011100100
DO_FREE_FORECAST: first
DT_ATMOS: 900
DT_RUNSEQ: 3600
envir: ng_fcst_baseline
EXP_CASE_NAME: ng_freefcst_baseline
FCST_HRS: 24
IC_FROM_FIX_DIR: 'YES'
NPROCS_ICE: 12
NPROCS_OCN: 16
NPZ: 127
OUTPUT_FH: '6 -1'
RES: 96
#WALLTIME_FORECAST: '00:45:00'
