ACCOUNT: epic
APP: NG-GODAS
COLDSTART: 'NO'
CUSTOM_JEDI_CONFIG_FLAG: 'YES'
CUSTOM_JEDI_CONFIG_PREFIX: test_3dvar
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2024111512
DATE_LAST_CYCLE: 2024111612
DATM_DATA_TYPE: gfs
DO_FREE_FORECAST: none
DT_ATMOS: 900
DT_MOM6: 1800
DT_RUNSEQ: 3600
envir: ng_soca_3dvar
EXP_CASE_NAME: ng_soca_3dvar
JEDI_ALGORITHM: 3dvar
JEDI_TYPE_SOCA: 'YES'
FCST_HRS: 24
NPROCS_ANALYSIS: 6
NPROCS_DATM: 12
NPROCS_ICE: 12
NPROCS_PREP_DATA: 96
NPROCS_OCN: 16
NPZ: 127
OUTPUT_FH: '6 -1'
RES: 96
