ACCOUNT: epic
APP: NG-GODAS
COLDSTART: 'NO'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2022080612
DATE_LAST_CYCLE: 2022080612
DATM_DATA_TYPE: gefs
DO_FREE_FORECAST: all
DT_ATMOS: 900
DT_MOM6: 900
DT_RUNSEQ: 1800
envir: ng_soca_gefs
EXP_CASE_NAME: ng_soca_gefs
FCST_HRS: 24
NPROCS_DATM: 12
NPROCS_ICE: 12
NPROCS_OCN: 16
NPZ: 127
OUTPUT_FH: '6 -1'
RES: 96
