ACCOUNT: epic
CUSTOM_JEDI_CONFIG_FLAG: 'YES'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2018041400
DATE_LAST_CYCLE: 2018041400
DO_FREE_FORECAST: ctest
JEDI_ALGORITHM: 3dvar
JEDI_TYPE_SNOW: 'NO'
JEDI_TYPE_SOCA: 'YES'
JEDI_TYPE_SOIL_MOISTURE: 'NO'
envir: soca_ctest_3dvar
EXP_CASE_NAME: soca_ctest_3dvar
RES: 96
