ACCOUNT: epic
APP: S2SWA
COLDSTART: 'YES'
COUPLER_CALENDAR: 2
#CUSTOM_JEDI_CONFIG_FLAG: 'YES'
#CUSTOM_JEDI_CONFIG_PATH:
#CUSTOM_JEDI_CONFIG_PREFIX: jedi_letkfoi_smops
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2021032206
DATE_LAST_CYCLE: 2021032206
DO_FREE_FORECAST: 'YES'
DT_ATMOS: 720
DT_RUNSEQ: 3600
EXP_CASE_NAME: s2swa_fcst_only_cold_00
FCST_HRS: 24
JEDI_ALGORITHM: letkf-oi
net: ufsda
NPROCS_ANALYSIS: 6
NPZ: 127
RES: 96
RUN: ufsda
