ACCOUNT: epic
APP: S2SWA
COLDSTART: 'YES'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2021032206
DATE_LAST_CYCLE: 2021032306
DO_FREE_FORECAST: all
DT_ATMOS: 720
DT_RUNSEQ: 3600
envir: fcst_restart
EXP_CASE_NAME: s2swa_freefcst_restart
FCST_HRS: 24
IC_FROM_FIX_DIR: 'YES'
NPZ: 127
OUTPUT_FH: '6 -1'
RES: 96
