flag:
  CUSTOM_JEDI_CONFIG_FLAG: 'TEMPLATE'
  JEDI_TYPE_SOCA: 'YES'
path:
#  JEDI_BIN_PATH:
parm:
  ACCOUNT: epic
  APP: NG-GODAS
  DATE_CYCLE_FREQ_HR: 24
  DATE_FIRST_CYCLE: 2021032212
  DATE_LAST_CYCLE: 2021032212
  DT_ATMOS: 900
  DT_MOM6: 1800
  DT_RUNSEQ: 3600
  envir: ng_soca_3dvar_gdas
  EXP_CASE_NAME: ng_soca_3dvar_gdas
  JEDI_ALGORITHM: 3dvar
  JEDI_BUNDLE_GDAS: gdas
  FCST_HRS: 24
  NPROCS_ANALYSIS: 96
  NPROCS_DATM: 12
  NPROCS_ICE: 12
  NPROCS_PREP_DATA: 96
  NPROCS_OCN: 16
  WORKFLOW_MANAGER: rocoto
