ACCOUNT: epic
APP: S2SWA
COLDSTART: 'YES'
CUSTOM_JEDI_CONFIG_FLAG: 'NO'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2025012000
DATE_LAST_CYCLE: 2025012100
DO_FREE_FORECAST: none
DT_ATMOS: 720
DT_RUNSEQ: 3600
envir: snowDA_3dvar
EXP_CASE_NAME: s2swa_snowDA_3dvar
FCST_HRS: 24
IC_FROM_FIX_DIR: 'NO'
JEDI_ALGORITHM: 3dvar
NPZ: 127
OBS_GHCN_SNOW: 'NO'
OBS_IMS_SNOW: 'YES'
OUTPUT_FH: '6 -1'
RES: 96
