flag:
  COLDSTART: 'YES'
  DO_FREE_FORECAST: all
  IC_FROM_FIX_DIR: 'YES'  
path:
parm:
  ACCOUNT: epic
  APP: NG-GODAS
  DATE_CYCLE_FREQ_HR: 12
  DATE_FIRST_CYCLE: 2011100100
  DATE_LAST_CYCLE: 2011100112
  DATM_DATA_TYPE: cfsr
  DT_ATMOS: 900
  DT_RUNSEQ: 3600
  envir: ng_fcst_cfsr
  EXP_CASE_NAME: ng_freefcst_cfsr
  FCST_HRS: 12
  NPROCS_DATM: 12
  NPROCS_ICE: 12
  NPROCS_OCN: 16
  OUTPUT_FH: '6 -1'

