ACCOUNT: epic
APP: S2SWA
COLDSTART: 'YES'
CUSTOM_JEDI_CONFIG_FLAG: 'NO'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2021032206
DATE_LAST_CYCLE: 2021032406
DO_FREE_FORECAST: first
DT_ATMOS: 720
DT_RUNSEQ: 3600
envir: soilmDA_letkfoi
EXP_CASE_NAME: s2swa_soilmDA_letkfoi
FCST_HRS: 72
IC_FROM_FIX_DIR: 'YES'
JEDI_ALGORITHM: letkf-oi
NPZ: 127
OBS_SMOPS: 'YES'
OUTPUT_FH: '6 -1'
RES: 96
