flag:
  JEDI_TYPE_FV3: 'YES'
  JEDI_TYPE_SOCA: 'NO'
path:
parm:
  ACCOUNT: epic
  DATE_CYCLE_FREQ_HR: 24
  DATE_FIRST_CYCLE: 2018041500
  DATE_LAST_CYCLE: 2018041500
  DO_FREE_FORECAST: ctest
  envir: fv3_ctest_3dvar
  EXP_CASE_NAME: fv3_ctest_3dvar
  JEDI_ALGORITHM: 3dvar
  JEDI_CTEST_NAME: 3dvar_gfs_aero
  NPROCS_ANALYSIS: 2
