flag:
  COLDSTART: 'YES'
  IC_FROM_FIX_DIR: 'YES'  
path:
parm:
  ACCOUNT: epic
  APP: NG-GODAS
  DATE_CYCLE_FREQ_HR: 6
  DATE_FIRST_CYCLE: 2021032206
  DATE_LAST_CYCLE: 2021032212
  DATM_DATA_TYPE: gfs
  DT_ATMOS: 900
  DT_RUNSEQ: 3600
  envir: ng_freefcst_ecf
  EXP_CASE_NAME: ng_freefcst_ecf
  FCST_HRS: 6
  NPROCS_DATM: 12
  NPROCS_ICE: 12
  NPROCS_OCN: 16
  OUTPUT_FH: '6 -1'
  RESTART_INTERVAL: '6 -1'
  TYPE_ANAL_FCST: fcst-only
  WORKFLOW_MANAGER: rocoto
