ACCOUNT: epic
APP: S2SWA
COLDSTART: 'YES'
CUSTOM_JEDI_CONFIG_FLAG: 'NO'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2021032206
DATE_LAST_CYCLE: 2021032306
DO_FREE_FORECAST: none
DT_ATMOS: 720
DT_RUNSEQ: 3600
envir: snowDA_3dvar
EXP_CASE_NAME: s2swa_snowDA_3dvar
FCST_HRS: 24
IC_FROM_FIX_DIR: 'YES'
JEDI_ALGORITHM: letkf-oi
NPZ: 127
OBS_GHCN_SNOW: 'YES'
OBS_SMOPS: 'NO'
OUTPUT_FH: '6 -1'
RES: 96
