ACCOUNT: epic
APP: S2SWA
COLDSTART: 'NO'
CUSTOM_JEDI_CONFIG_FLAG: 'NO'
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2021032506
DATE_LAST_CYCLE: 2021032606
DO_FREE_FORECAST: none
DT_ATMOS: 720
DT_RUNSEQ: 3600
envir: snowDA_3dvar
EXP_CASE_NAME: s2swa_snowDA_3dvar
FCST_HRS: 24
IC_FROM_FIX_DIR: 'NO'
JEDI_ALGORITHM: 3dvar
JEDI_TYPE_SNOW: 'YES'
JEDI_TYPE_SOCA: 'NO'
JEDI_TYPE_SOIL_MOISTURE: 'NO'
NPZ: 127
OBS_GHCN_SNOW: 'YES'
OBS_IMS_SNOW: 'NO'
OUTPUT_FH: '6 -1'
RES: 96
